import { CarProps } from "@/types";

const carsData: CarProps[] = [
  {
    make: "Toyota",
    model: "camry",
    year: 2023,
    fuel_type: "gas",
    city_mpg: 28,
    highway_mpg: 39,
    combination_mpg: 32,
    transmission: "a",
    drive: "fwd",
    cylinders: 4,
    displacement: 2.5,
    class: "midsize car",
  },
  {
    make: "Honda",
    model: "civic",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 31,
    highway_mpg: 40,
    combination_mpg: 35,
    transmission: "a",
    drive: "fwd",
    cylinders: 4,
    displacement: 1.5,
    class: "compact car",
  },
  {
    make: "Tesla",
    model: "model 3",
    year: 2023,
    fuel_type: "electricity",
    city_mpg: 141,
    highway_mpg: 127,
    combination_mpg: 134,
    transmission: "a",
    drive: "rwd",
    cylinders: 0,
    displacement: 0,
    class: "midsize car",
  },
  {
    make: "Ford",
    model: "mustang",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 16,
    highway_mpg: 25,
    combination_mpg: 19,
    transmission: "m",
    drive: "rwd",
    cylinders: 8,
    displacement: 5.0,
    class: "subcompact car",
  },
  {
    make: "BMW",
    model: "3 series",
    year: 2023,
    fuel_type: "gas",
    city_mpg: 26,
    highway_mpg: 36,
    combination_mpg: 30,
    transmission: "a",
    drive: "rwd",
    cylinders: 4,
    displacement: 2.0,
    class: "compact car",
  },
  {
    make: "Chevrolet",
    model: "silverado",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 16,
    highway_mpg: 21,
    combination_mpg: 18,
    transmission: "a",
    drive: "4wd",
    cylinders: 8,
    displacement: 5.3,
    class: "standard pickup truck",
  },
  {
    make: "Tesla",
    model: "model y",
    year: 2023,
    fuel_type: "electricity",
    city_mpg: 129,
    highway_mpg: 117,
    combination_mpg: 123,
    transmission: "a",
    drive: "awd",
    cylinders: 0,
    displacement: 0,
    class: "small suv",
  },
  {
    make: "Subaru",
    model: "outback",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 26,
    highway_mpg: 33,
    combination_mpg: 29,
    transmission: "a",
    drive: "awd",
    cylinders: 4,
    displacement: 2.5,
    class: "small station wagons",
  },
  {
    make: "Porsche",
    model: "911",
    year: 2023,
    fuel_type: "gas",
    city_mpg: 18,
    highway_mpg: 25,
    combination_mpg: 21,
    transmission: "a",
    drive: "rwd",
    cylinders: 6,
    displacement: 3.0,
    class: "subcompact car",
  },
  {
    make: "Jeep",
    model: "wrangler",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 17,
    highway_mpg: 23,
    combination_mpg: 19,
    transmission: "m",
    drive: "4wd",
    cylinders: 4,
    displacement: 2.0,
    class: "special purpose vehicle",
  },
  {
    make: "Hyundai",
    model: "ioniq 6",
    year: 2023,
    fuel_type: "electricity",
    city_mpg: 151,
    highway_mpg: 127,
    combination_mpg: 140,
    transmission: "a",
    drive: "rwd",
    cylinders: 0,
    displacement: 0,
    class: "midsize car",
  },
  {
    make: "Mazda",
    model: "cx-5",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 24,
    highway_mpg: 30,
    combination_mpg: 27,
    transmission: "a",
    drive: "awd",
    cylinders: 4,
    displacement: 2.5,
    class: "small suv",
  },
  {
    make: "Toyota",
    model: "tacoma",
    year: 2021,
    fuel_type: "gas",
    city_mpg: 18,
    highway_mpg: 24,
    combination_mpg: 20,
    transmission: "a",
    drive: "4wd",
    cylinders: 6,
    displacement: 3.5,
    class: "standard pickup truck",
  },
  {
    make: "Honda",
    model: "cr-v",
    year: 2023,
    fuel_type: "gas",
    city_mpg: 28,
    highway_mpg: 34,
    combination_mpg: 30,
    transmission: "a",
    drive: "awd",
    cylinders: 4,
    displacement: 1.5,
    class: "small suv",
  },
  {
    make: "Ford",
    model: "f-150",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 18,
    highway_mpg: 24,
    combination_mpg: 20,
    transmission: "a",
    drive: "4wd",
    cylinders: 6,
    displacement: 3.5,
    class: "standard pickup truck",
  },
  {
    make: "Volkswagen",
    model: "golf",
    year: 2022,
    fuel_type: "gas",
    city_mpg: 29,
    highway_mpg: 36,
    combination_mpg: 32,
    transmission: "m",
    drive: "fwd",
    cylinders: 4,
    displacement: 2.0,
    class: "compact car",
  },
  {
    make: "Nissan",
    model: "altima",
    year: 2021,
    fuel_type: "gas",
    city_mpg: 27,
    highway_mpg: 38,
    combination_mpg: 31,
    transmission: "a",
    drive: "fwd",
    cylinders: 4,
    displacement: 2.5,
    class: "midsize car",
  },
  {
    make: "Kia",
    model: "ev6",
    year: 2023,
    fuel_type: "electricity",
    city_mpg: 134,
    highway_mpg: 101,
    combination_mpg: 117,
    transmission: "a",
    drive: "awd",
    cylinders: 0,
    displacement: 0,
    class: "small suv",
  },
];

export default carsData;
